- name: Symlink kde plasma themes folder
  when: ansible_os_family == "Archlinux"
  file:
    src: "{{ dotfiles_home }}/roles/kde/files/theme/plasma"
    dest: "{{ dotfiles_user_home }}/.local/share/plasma"
    state: link
  tags:
    - install
    - kde

- name: Symlink kde plasma wallpapers folder
  when: ansible_os_family == "Archlinux"
  file:
    src: "{{ dotfiles_home }}/roles/kde/files/theme/wallpapers"
    dest: "{{ dotfiles_user_home }}/.local/share/wallpapers"
    state: link
  tags:
    - install
    - kde

- name: Find all files in kde/files/config
  find:
    paths: "{{ dotfiles_home }}/roles/kde/files/config"
  register: find

- name: Create symlinks to kde config
  when: ansible_os_family == "Archlinux"
  file:
    src: "{{ item.path }}"
    path: "{{ dotfiles_user_home }}/.config/{{ item.path | basename }}"
    state: link
  with_items: "{{ find.files }}"
  tags:
    - install
    - kde

