- name: Creates directory ~/.local/bin
  file:
    path: "{{ dotfiles_user_home }}/.local/bin"
    state: directory
  tags:
    - install
    - scripts

- name: Create symlink to ~/.local/bin/tmux-sessionizer
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/tmux-sessionizer"
    dest: "{{ dotfiles_user_home }}/.local/bin/tmux-sessionizer"
    state: link
  tags:
    - install
    - scripts

- name: Create symlink to ~/.local/bin/cht.sh
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/cht.sh"
    dest: "{{ dotfiles_user_home }}/.local/bin/cht.sh"
    state: link
  tags:
    - install
    - scripts

- name: Create symlink to ~/.local/bin/run-or-raise
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/run-or-raise"
    dest: "{{ dotfiles_user_home }}/.local/bin/run-or-raise"
    state: link
  tags:
    - install
    - scripts

- name: Create symlink to ~/.local/bin/ssh-ask-pass.sh
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/ssh-ask-pass.sh"
    dest: "{{ dotfiles_user_home }}/.local/bin/ssh-ask-pass.sh"
    state: link
  tags:
    - install
    - scripts

- name: Create symlink to ~/.local/bin/better-branch.sh
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/better-branch.sh"
    dest: "{{ dotfiles_user_home }}/.local/bin/better-branch.sh"
    state: link
  tags:
    - install
    - scripts

- name: Create symlink to ~/.local/bin/open-webui.sh
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/open-webui.sh"
    dest: "{{ dotfiles_user_home }}/.local/bin/open-webui.sh"
    state: link
  tags:
    - install
    - scripts
