- name: Creates directory ~/.local/bin
  file:
    path: "{{ dotfiles_user_home }}/.local/bin"
    state: directory

- name: Create symlink to ~/.local/bin/tmux-sessionizer
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/tmux-sessionizer"
    dest: "{{ dotfiles_user_home }}/.local/bin/tmux-sessionizer"
    state: link

- name: Create symlink to ~/.local/bin/cht.sh
  file:
    src: "{{ dotfiles_home }}/roles/scripts/files/cht.sh"
    dest: "{{ dotfiles_user_home }}/.local/bin/cht.sh"
    state: link
