- name: Download yay
  when: ansible_os_family == "Archlinux"
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ dotfiles_user_home }}/.yay"
  tags:
    - install
    - yay

- name: Install yay
  when: ansible_os_family == "Archlinux"
  shell:
    cmd: makepkg -sfi --noconfirm
    chdir: "{{ dotfiles_user_home }}/.yay"
  tags:
    - install
    - yay

- name: Generate a development package database for *-git packages that were installed without yay. This command should only be run once.
  when: ansible_os_family == "Archlinux"
  raw: "yay -Y --gendb"
  tags:
    - install
    - yay

- name: Check for development package updates
  when: ansible_os_family == "Archlinux"
  raw: "yay -Syu --devel --noconfirm"
  tags:
    - install
    - yay

- name: Make development package updates permanently enabled (yay and yay -Syu will then always check dev packages)
  when: ansible_os_family == "Archlinux"
  raw: "yay -Y --devel --save"
  tags:
    - install
    - yay

- name: Create 'aur_builder' to perform yay operations
  when: ansible_os_family == "Archlinux"
  become: yes
  block:
  - name: Create the `aur_builder` user
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'
