#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items="`find ~/work -maxdepth 1 -mindepth 1 -type d`
`find ~/personal -maxdepth 1 -mindepth 1 -type d`
$HOME/personal
$HOME/work
$HOME/.dotfiles"
    selected=`echo "$items" | fzf`
fi

if [[ ! -z "$selected" ]]; then
  tmux_session_name=`basename $selected | tr . _`

  tmux switch-client -t $tmux_session_name
  if [[ $? -eq 0 ]]; then
      exit 0
  fi

  tmux new-session -c $selected -d -s $tmux_session_name && tmux switch-client -t $tmux_session_name || tmux new -c $selected -A -s $tmux_session_name
fi

