- name: Install system packages
  when: ansible_os_family == "Archlinux"
  become: true
  community.general.pacman:
    name:
      - base-devel
      - brave-browser
      - dbeaver
      - discord
      - docker
      - firefox
      - fzf
      - gimp
      - git
      - linux-headers
      - noto-fonts
      - noto-fonts-emoji
      - thunderbird
      - ripgrep
      # Required to copy to clipboard in vim on X11
      - xclip
      - yay
      - wmctrl
    state: present
  tags:
    - install
    - core

- name: Complete docker installation
  when: ansible_os_family == "Archlinux"
  block:
    - name: Add current user to docker group
      become: true
      user:
        name: akyrey
        groups: docker
        append: yes
    - name: Activate group changes
      ansible.builtin.command: newgrp docker
    - name: Enable docker service
      become: true
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
    - name: Enable containerd service
      become: true
      ansible.builtin.systemd_service:
        name: containerd.service
        enabled: true
    - name: Symlink daemon.json
      become: true
      file:
        src: "{{ dotfiles_home }}/roles/core-setup/files/daemon.json"
        dest: "/etc/docker/daemon.json"
        state: link
  tags:
    - install
    - core

- name: Update all packages to their latest version
  when: ansible_os_family == "Archlinux"
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  tags:
    - update
    - core

- name: Install aur system packages
  when: ansible_os_family == "Archlinux"
  kewlfft.aur.aur:
    name:
      - bitwarden
      - docker-buildx
      - docker-compose
      - google-chrome
      - layan-cursor-theme-git
      - lazidocker
      - lazigit
      - microsoft-edge-stable-bin
      - nvidia-container-toolkit
      - obsidian
      - papirus-icon-theme
      - phpstorm
      - phpstorm-jre
      - postman
      - signal-desktop
      - slack-desktop
      - spotify
      - visual-studio-code-bin
      # Required to copy to clipboard in vim on X11
      - wl-clipboard
    state: present
  tags:
    - install
    - core

- name: Update all AUR packages to their latest version
  when: ansible_os_family == "Archlinux"
  kewlfft.aur.aur:
    aur_only: yes
    update_cache: yes
    upgrade: yes
  tags:
    - update
    - core

- name: Install System76 dependencies
  when: ansible_system_vendor == "System76" and ansible_os_family == "Archlinux"
  block:
    - name: Install System76 drivers
      kewlfft.aur.aur:
        name:
          - firmware-manager-git
          - system76-driver
          - system76-firmware-daemon-git
    - name: Enable System76 driver
      become: true
      ansible.builtin.systemd_service:
        name: system76
        enabled: true
    - name: Enable System76 firmware daemon
      become: true
      ansible.builtin.systemd_service:
        name: system76-firmware-daemon
        enabled: true
    - name: Add user to 'adm' group
      become: true
      user:
        name: akyrey
        groups: adm
        append: yes
  tags:
    - install
    - core
