- import_tasks: roles/core-setup/tasks/arch-linux.yml
  when: ansible_os_family == "Archlinux"
  tags:
    - install
    - core

- import_tasks: roles/core-setup/tasks/debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - install
    - core

- name: Enable services
  become: yes
  ansible.builtin.systemd:
    enabled: yes
    name: docker
    state: started
  tags:
    - install
    - core

- name: Add user to new groups
  become: yes
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  tags:
    - install
    - core

- name: Copy docker daemon.json
  become: yes
  ansible.builtin.template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
  notify: restart_docker
  tags:
    - install
    - core

- name: Clone Nerd Fonts repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: "{{ dotfiles_user_home }}/.nerd-fonts"
  register: nerd_fonts_repo_clone
  tags:
    - install
    - update
    - core

- name: Install Caskaydia Cove Nerd Font
  when: nerd_fonts_repo_clone.changed
  ansible.builtin.shell: ./install.sh CascadiaCode
  args:
    chdir: "{{ dotfiles_user_home }}/.nerd-fonts"
  tags:
    - install
    - update
    - core
