- name: Install system packages
  when: ansible_os_family == "Archlinux"
  become: yes
  community.general.pacman:
    name:
      - discord
      - docker
      - fzf
      - noto-fonts
      - noto-fonts-emoji
      - ripgrep
      - xclip
      - wmctrl
    state: present
  tags:
    - install
    - core

- name: Install aur system packages
  when: ansible_os_family == "Archlinux"
  kewlfft.aur.aur:
    name:
      - bitwarden
      - google-chrome
      - latte-dock-git
      - layan-cursor-theme-git
      - microsoft-edge-stable-bin
      - obsidian
      - papirus-icon-theme
      - postman
    state: present
  tags:
    - install
    - core

- name: Enable services
  when: ansible_os_family == "Archlinux"
  become: yes
  ansible.builtin.systemd:
    enabled: yes
    name: docker
    state: started
  tags:
    - install
    - core

- name: Add user to new groups
  when: ansible_os_family == "Archlinux"
  become: yes
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  tags:
    - install
    - core

- name: Copy docker daemon.json
  when: ansible_os_family == "Archlinux"
  become: yes
  ansible.builtin.template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
  notify: restart_docker
  tags:
    - install
    - core

- name: Symlink latte-dock layout
  file:
    src: "{{ dotfiles_home}}/roles/core-setup/files/akyrey.layout.latte"
    dest: "{{dotfiles_user_home}}/.config/latte/akyrey.layout.latte"
    state: link 
    force: yes
  tags:
    - install
    - core

- name: Clone Nerd Fonts repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: "{{ dotfiles_user_home }}/.nerd-fonts"
  register: nerd_fonts_repo_clone
  tags:
    - install
    - core

- name: Install Caskaydia Cove Nerd Font
  when: nerd_fonts_repo_clone.changed
  ansible.builtin.shell: ./install.sh CascadiaCode
  args:
    chdir: "{{ dotfiles_user_home }}/.nerd-fonts"
  tags:
    - install
    - core
