- name: Install system packages
  when: ansible_os_family == "Archlinux"
  become: yes
  community.general.pacman:
    name:
      - fzf
      - noto-fonts
      - noto-fonts-emoji
      - ripgrep
    state: present
  tags:
    - install
    - core

- name: Install aur system packages
  when: ansible_os_family == "Archlinux"
  kewlfft.aur.aur:
    name:
      - bitwarden
      - latte-dock-git
      - microsoft-edge-stable-bin
      - obsidian
      - postman
    state: present
  tags:
    - install
    - core

- name: Clone Nerd Fonts repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: "{{ dotfiles_user_home }}/.nerd-fonts"
  register: nerd_fonts_repo_clone
  tags:
    - install
    - core

- name: Install Caskaydia Cove Nerd Font
  when: nerd_fonts_repo_clone.changed
  ansible.builtin.shell: ./install.sh CascadiaCode
  args:
    chdir: "{{ dotfiles_user_home }}/.nerd-fonts"
  tags:
    - install
    - core
