- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dotfiles_user_home }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install default ssh key
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/id_rsa"
    dest: "{{ dotfiles_user_home }}/.ssh/id_rsa"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install default ssh public key
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/id_rsa.pub"
    dest: "{{ dotfiles_user_home }}/.ssh/id_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Install codecommit ssh key
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/codecommit_rsa"
    dest: "{{ dotfiles_user_home }}/.ssh/codecommit_rsa"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install codecommit ssh public key
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/codecommit_rsa.pub"
    dest: "{{ dotfiles_user_home }}/.ssh/codecommit_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Install BitBucket ssh key
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/bitbucket_rsa"
    dest: "{{ dotfiles_user_home }}/.ssh/bitbucket_rsa"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install BitBucket ssh public key
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/bitbucket_rsa.pub"
    dest: "{{ dotfiles_user_home }}/.ssh/bitbucket_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh config
  copy:
    src: "{{ dotfiles_home }}/roles/ssh/files/config"
    dest: "{{ dotfiles_user_home }}/.ssh/config"
    mode: 0700
  tags:
    - dotfiles
    - install
    - ssh
