- import_tasks: roles/zsh/tasks/arch-linux.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: roles/zsh/tasks/debian.yml
  when: ansible_os_family == "Debian"

- name: Check for oh-my-zsh installation
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  raw: "sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
  when: not oh_my_zsh_stat.stat.exists

- name: Install powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Check for .zshrc
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Symlink .zshrc
  file:
    src: "{{ dotfiles_home}}/roles/zsh/files/zshrc"
    dest: "{{dotfiles_user_home}}/.zshrc"
    state: link 
