- name: Check if AWS cli is already installed
  stat:
    path: /usr/local/bin/aws
  register: aws_cli
  tags:
    - install
    - aws

- include_tasks: roles/aws/tasks/macos.yml
  when: not aws_cli.stat.exists and ansible_os_family == "Darwin"
  tags:
    - install
    - aws

- include_tasks: roles/aws/tasks/linux.yml
  when: not aws_cli.stat.exists and (ansible_os_family == "Archlinux" or ansible_os_family == "Debian")
  tags:
    - install
    - aws
