- import_tasks: roles/git/tasks/arch-linux.yml
  when: ansible_os_family == "Archlinux"
  tags:
    - install
    - git-personal
    - git-euronovate

- import_tasks: roles/git/tasks/debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - install
    - git-personal
    - git-euronovate

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes
  tags:
    - install
    - git-personal
    - git-euronovate

- name: Symlink gitconfig file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitconfig"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
    state: link
    force: yes
  tags:
    - install

- name: Symlink gitconfig-personal file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitconfig-personal"
    dest: "{{ dotfiles_user_home }}/.gitconfig-personal"
    state: link
    force: yes
  tags:
    - install

- name: Symlink gitconfig-work file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitconfig-work"
    dest: "{{ dotfiles_user_home }}/.gitconfig-work"
    state: link
    force: yes
  tags:
    - install
