- name: Add wezterm repo
  when: ansible_os_family == "Debian"
  become: yes
  shell: curl -LO https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/wezterm-20230712-072601-f4abf8fd.Ubuntu22.04.deb; apt install -y ./wezterm-20230712-072601-f4abf8fd.Ubuntu22.04.deb; rm wezterm-20230712-072601-f4abf8fd.Ubuntu22.04.deb
  tags:
    - install
    - wezterm

- name: Symlink configurations
  when: ansible_os_family == "Archlinux" or ansible_os_family == "Debian"
  file:
    src: "{{ dotfiles_home }}/roles/wezterm/files/wezterm.lua"
    dest: "{{ dotfiles_user_home }}/.config/wezterm/wezterm.lua"
    state: link
  tags:
    - install
    - wezterm
