- name: Add wezterm repo
  when: ansible_os_family == "Debian"
  become: true
  shell: curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg \ echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
  tags:
    - install
    - wezterm

- name: Install wezterm
  when: ansible_os_family == "Debian"
  become: true
  ansible.builtin.apt:
    name:
      - wezterm
    state: present
    update_cache: yes
  tags:
    - install
    - wezterm

- name: Install wezterm
  when: ansible_os_family == "Archlinux"
  become: true
  community.general.pacman:
    name:
      - ttf-nerd-fonts-symbols-mono
      - wezterm
    state: present
  tags:
    - install
    - wezterm

- name: Symlink configurations
  when: ansible_os_family == "Archlinux" or ansible_os_family == "Debian"
  file:
    src: "{{ dotfiles_home }}/roles/wezterm/files/wezterm.lua"
    dest: "{{ dotfiles_user_home }}/.config/wezterm/wezterm.lua"
    state: link
  tags:
    - install
    - wezterm

- name: Symlink background
  when: ansible_os_family == "Archlinux" or ansible_os_family == "Debian"
  file:
    src: "{{ dotfiles_home }}/roles/wezterm/files/background.png"
    dest: "{{ dotfiles_user_home }}/.config/wezterm/background.png"
    state: link
  tags:
    - install
    - wezterm
