- import_tasks: roles/tmux/tasks/arch-linux.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: roles/tmux/tasks/debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: roles/tmux/tasks/macos.yml
  when: ansible_os_family == "Darwin"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
    force: yes
