- name: Install required packages to build nvim on Debian
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake 
      - g++
      - pkg-config
      - cmake
      - unzip
      - curl
      - ripgrep
    state: present

