- import_tasks: roles/nvim/tasks/arch-linux.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: roles/nvim/tasks/macos.yml
  when: ansible_os_family == "Darwin"

- name: Clone nvim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ dotfiles_user_home }}/.neovim"
    version: "stable"

- name: Build nvim in build/bin folder
  community.general.make:
    chdir: "{{ dotfiles_user_home }}/.neovim"

- name: Symlink neovim files
  file:
    src: "{{ dotfiles_user_home }}/.neovim/build/bin"
    dest: "/usr/bin/nvim"
    state: link
    become: yes

- name: Symlink neovim configurations
  file:
    src: "{{ dotfiles_home }}/roles/nvim/files"
    dest: "~/.config/nvim"
    state: link
