- import_tasks: roles/nvim/tasks/debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: roles/nvim/tasks/arch-linux.yml
  when: ansible_os_family == "Archlinux"

- import_tasks: roles/nvim/tasks/macos.yml
  when: ansible_os_family == "Darwin"

- name: Clone nvim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ dotfiles_user_home }}/.neovim"
    version: stable
    force: yes

- name: Build nvim in build/bin folder
  become: yes
  community.general.make:
    chdir: "{{ dotfiles_user_home }}/.neovim"
    target: install
    params:
      CMAKE_BUILD_TYPE: Release

- name: Symlink neovim files
  become: yes
  file:
    src: "{{ dotfiles_user_home }}/.neovim/build/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link

- name: Symlink neovim configurations
  file:
    src: "{{ dotfiles_home }}/roles/nvim/files"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link
