- name: Install neovim
  raw: curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage \;\
       chmod u+x nvim.appimage \;\
       ./nvim.appimage


- name: Symlink neovim configurations
  file:
    src: "{{ dotfiles_home }}/roles/vim/files"
    dest: "~/.config/nvim"
    state: link
